### ISSUE TITLE
Using local storage?

### ISSUE THREAD

**Issue by mizterp** [HangYang/LinkSaver#1]
Any chance you could provide a version that uses local/synced storage instead of a third-party website?

Would also be cool to see a list of saved links without doing a search.

**Comment by HangYang** [comment]
what do you want to do with it?

**Comment by mizterp** [comment]
Was mainly looking for a solution to keep a private list of links synced between all my machines where I use Chrome.

**Comment by HangYang** [comment]
how about using bookmark? it will be keep synced after you login into Chrome.

**Comment by mizterp** [comment]
Doing that now yeah, was just hoping to keep a list separate from my normal bookmarks. Will maybe check into creating a basic extension that reads/writes to a specific bookmark folder.
